Repository alibaba/DeepRec, pull requests merged in 2021-12, with the labels that each got.

#7 [docs] Update README and user docs.
  README.md
  docs/index.md
Labels: documentation

#13 [docs] Update README, docs and workflow
  .github/workflows/ubuntu18.04-py3.6-cibuild.yaml
  .github/workflows/ubuntu18.04-py3.6-cuda11.2-cibuild.yaml
  README.md
  docs/Dynamic-dimension-Embedding-Variable.md
  docs/index.md
Labels: documentation

#14 [Modelzoo] Improve DLRM's AUC in default setting.
  modelzoo/DLRM/train.py
  modelzoo/WDL/train.py
Labels: bug

#15 Update README and index of docs, add get start docs
  README.md
  docs/Compile-And-Install.md
  docs/index.md
Labels: documentation

#9 [Embedding] Add EV Initializer for initializers which need static shape.
  tensorflow/core/framework/embedding/embedding_config.h
  tensorflow/core/framework/embedding/embedding_filter.h
  tensorflow/core/framework/embedding/embedding_var.h
  tensorflow/core/kernels/embedding_variable_ops_test.cc
  tensorflow/core/kernels/kv_variable_ops.cc
  tensorflow/core/ops/kv_variable_ops.cc
  tensorflow/python/ops/embedding_variable_ops_test.py
  tensorflow/python/ops/kv_variable_ops.py
  tensorflow/python/ops/variable_scope.py
  tensorflow/python/ops/variables.py
  tensorflow/python/training/saving/saveable_object_util.py
  tensorflow/tools/api/golden/v1/tensorflow.-embedding-variable-option.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.-initializer-option.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.raw_ops.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.raw_ops.pbtxt
Labels: enhancement
