Repository alibaba/DeepRec, pull requests merged in 2022-07, with the labels that each got.

#270 [IO] Add Parquet Dataset Support.
  tensorflow/core/BUILD
  tensorflow/core/api_def/base_api/api_def_ParquetTabularDatasetV1.pbtxt
  tensorflow/core/kernels/data/BUILD
  tensorflow/core/kernels/data/arrow_util.cc
  tensorflow/core/kernels/data/arrow_util.h
  tensorflow/core/kernels/data/eigen.h
  tensorflow/core/kernels/data/parquet_batch_reader.cc
  tensorflow/core/kernels/data/parquet_batch_reader.h
  tensorflow/core/kernels/data/parquet_dataset_ops.cc
  tensorflow/core/kernels/data/parquet_dataset_ops.h
  tensorflow/core/kernels/data/parquet_pybind.cc
  tensorflow/core/ops/parquet_ops.cc
  tensorflow/core/platform/s3/aws_logging.h
  tensorflow/python/BUILD
  tensorflow/python/data/experimental/__init__.py
  tensorflow/python/data/experimental/kernel_tests/BUILD
  tensorflow/python/data/experimental/kernel_tests/parquet_dataset_ops_test.py
  tensorflow/python/data/experimental/ops/BUILD
  tensorflow/python/data/experimental/ops/dataframe.py
  tensorflow/python/data/experimental/ops/parquet_dataset_ops.py
  tensorflow/python/data/experimental/ops/parquet_pybind.py
  tensorflow/tools/api/golden/v1/tensorflow.-storage-option.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.raw_ops.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.raw_ops.pbtxt
  tensorflow/workspace.bzl
  third_party/arrow.BUILD
  third_party/aws/BUILD.bazel
  third_party/aws/workspace.bzl
  third_party/aws_util/BUILD
  third_party/aws_util/aws_c_cal.BUILD
  third_party/aws_util/aws_c_common.BUILD
  third_party/aws_util/aws_c_event_stream.BUILD
  third_party/aws_util/aws_c_io.BUILD
  third_party/aws_util/aws_checksums.BUILD
  third_party/brotli.BUILD
  third_party/bzip2.BUILD
  third_party/hadoop/BUILD
  third_party/rapidjson.BUILD
  third_party/snappy.BUILD
  third_party/thrift.BUILD
  third_party/xsimd.BUILD
  third_party/zstd.BUILD
Labels: enhancement

#295 [Runtime] Fix create devices function miss return status bug.
  tensorflow/core/common_runtime/device_factory.h
Labels: bug

#294 [Embedding] Fix BatchCache coredump in background thread.
  tensorflow/core/framework/embedding/cache.h
  tensorflow/core/framework/embedding/embedding_var.h
  tensorflow/core/framework/embedding/multilevel_embedding.h
  tensorflow/core/kernels/kv_variable_ops.cc
  tensorflow/python/ops/embedding_variable_ops_test.py
Labels: bug

#312 [Serving] Support multiple languages.
  serving/sdk/go/README.md
  serving/sdk/go/demo.go
  serving/sdk/go/processor.h
  serving/sdk/java/README.md
  serving/sdk/java/src/main/java/Demo.java
  serving/sdk/python/README.md
  serving/sdk/python/demo.py
Labels: ASoC 2022

#320 [UT] Fix random failure of incr_ckpt_test in GPU test.
  tensorflow/python/training/incr_ckpt_test.py
Labels: bug

#333 [Embedding] Fix: StorageType{PMEM_MEMKIND, PMEM_LIBPMEM} is not Multi…
  tensorflow/core/framework/embedding/multilevel_embedding.h
Labels: bug

#329 [Docs] Update oneDNN compile options description.
  docs/oneDNN.md
Labels: documentation

#289 [Embedding] Multi-tier Embedding support HBM.
  cibuild/gpu-ut/gpu-python-ut.sh
  tensorflow/core/BUILD
  tensorflow/core/framework/embedding/batch.cu.cc
  tensorflow/core/framework/embedding/batch.h
  tensorflow/core/framework/embedding/embedding_filter.h
  tensorflow/core/framework/embedding/embedding_var.h
  tensorflow/core/framework/embedding/lockless_hash_map_cpu.h
  tensorflow/core/framework/embedding/multilevel_embedding.h
  tensorflow/core/framework/embedding/value_ptr.h
  tensorflow/core/kernels/BUILD
  tensorflow/core/kernels/embedding_variable_ops_test.cc
  tensorflow/core/kernels/kv_variable_ops.cc
  tensorflow/core/kernels/training_ali_ops.cc
  tensorflow/python/ops/embedding_variable_ops_test.py
Labels: enhancement

#337 [ModelZoo] Optimize DIN's BF16 perfermance.
  modelzoo/DIN/train.py
Labels: performance
