Repository alibaba/DeepRec, pull requests merged in 2022-01, with the labels that each got.

#26 [docs] Update TensorPoolAllocator doc and add vmem doc
  docs/CPU-Memory-Optimization.md
  docs/GPU-Memory-Optimization.md
  docs/GPU-Virtual-Memory.md
  docs/TensorPoolAllocator.md
  docs/index.md
Labels: documentation

#29 [CIBUILD] Update the event triggers of workflow
  .github/workflows/ubuntu18.04-py3.6-cibuild-build-wheel.yaml
  .github/workflows/ubuntu18.04-py3.6-cibuild-c-unit-test.yaml
  .github/workflows/ubuntu18.04-py3.6-cibuild-cc-unit-test.yaml
  .github/workflows/ubuntu18.04-py3.6-cibuild-contrib-unit-test.yaml
  .github/workflows/ubuntu18.04-py3.6-cibuild-core-unit-test.yaml
  .github/workflows/ubuntu18.04-py3.6-cibuild-examples-unit-test.yaml
  .github/workflows/ubuntu18.04-py3.6-cibuild-java-unit-test.yaml
  .github/workflows/ubuntu18.04-py3.6-cibuild-js-unit-test.yaml
  .github/workflows/ubuntu18.04-py3.6-cibuild-python-unit-test.yaml
  .github/workflows/ubuntu18.04-py3.6-cibuild-stream_executor-unit-test.yaml
  .github/workflows/ubuntu18.04-py3.6-cuda11.2-cibuild-build-wheel.yaml
  .github/workflows/ubuntu18.04-py3.6-cuda11.2-cibuild-c-unit-test.yaml
  .github/workflows/ubuntu18.04-py3.6-cuda11.2-cibuild-cc-unit-test.yaml
  .github/workflows/ubuntu18.04-py3.6-cuda11.2-cibuild-contrib-unit-test.yaml
  .github/workflows/ubuntu18.04-py3.6-cuda11.2-cibuild-core-unit-test.yaml
  .github/workflows/ubuntu18.04-py3.6-cuda11.2-cibuild-examples-unit-test.yaml
  .github/workflows/ubuntu18.04-py3.6-cuda11.2-cibuild-java-unit-test.yaml
  .github/workflows/ubuntu18.04-py3.6-cuda11.2-cibuild-js-unit-test.yaml
  .github/workflows/ubuntu18.04-py3.6-cuda11.2-cibuild-python-unit-test.yaml
  .github/workflows/ubuntu18.04-py3.6-cuda11.2-cibuild-stream_executor-unit-test.yaml
Labels: cibuild

#31 [CIBUILD] Improve parallelism of workflow
  cibuild/cpu-ut/cpu-c-ut.sh
  cibuild/cpu-ut/cpu-cc-ut.sh
  cibuild/cpu-ut/cpu-contrib-ut.sh
  cibuild/cpu-ut/cpu-core-ut.sh
  cibuild/cpu-ut/cpu-examples-ut.sh
  cibuild/cpu-ut/cpu-java-ut.sh
  cibuild/cpu-ut/cpu-js-ut.sh
  cibuild/cpu-ut/cpu-python-ut.sh
  cibuild/cpu-ut/cpu-stream_executor-ut.sh
  cibuild/gpu-ut/gpu-c-ut.sh
  cibuild/gpu-ut/gpu-cc-ut.sh
  cibuild/gpu-ut/gpu-contrib-ut.sh
  cibuild/gpu-ut/gpu-core-ut.sh
  cibuild/gpu-ut/gpu-examples-ut.sh
  cibuild/gpu-ut/gpu-java-ut.sh
  cibuild/gpu-ut/gpu-js-ut.sh
  cibuild/gpu-ut/gpu-python-ut.sh
  cibuild/gpu-ut/gpu-stream_executor-ut.sh
Labels: cibuild

#34 [Distributed] Rename star_server protocol name.
  docs/StarServer.md
  tensorflow/contrib/star/seastar/seastar_server_lib.cc
  tensorflow/contrib/star/star_server_base_lib.cc
  tensorflow/contrib/star/star_server_base_lib.h
  tensorflow/contrib/star_server/star_server_lib.cc
  tensorflow/core/distributed_runtime/master_env.h
  tensorflow/core/distributed_runtime/master_session.cc
  tensorflow/core/distributed_runtime/message_wrappers.h
  tensorflow/core/protobuf/config.proto
  tensorflow/core/protobuf/worker.proto
  tensorflow/tools/api/golden/v1/tensorflow.-config-proto.pbtxt
Labels: refactoring

#33 [Embedding] Fix: EV ApplyOp ResourceHandle lack of UnrefScope.
  tensorflow/core/kernels/incr_save_restore_ops.cc
  tensorflow/core/kernels/save_restore_v2_ops.cc
  tensorflow/core/kernels/training_ali_ops.cc
Labels: bug

#37 [Embedding] Update fused embedding perf benchmark.
  modelzoo/features/GPUFusedEmbedding/.gitignore
  modelzoo/features/GPUFusedEmbedding/DLRM/README.md
  modelzoo/features/GPUFusedEmbedding/DLRM/train.py
  modelzoo/features/GPUFusedEmbedding/DeepFM/README.md
  modelzoo/features/GPUFusedEmbedding/WDL/README.md
Labels: benchmark

#40 [docs] Update fused embedding perf benchmark in EmbeddingFusion document.
  docs/Fused-Embedding.md
Labels: benchmark

#32 [SOK] Update ReadMe and re-test DLRM performance.
  modelzoo/SOK/DLRM/ReadMe.md
  modelzoo/SOK/DLRM/model/models.py
  modelzoo/SOK/DLRM/model/strategy_wrapper.py
  modelzoo/SOK/DLRM/train_stand.py
  sparse_operation_kit/ReadMe.md
  sparse_operation_kit/request.sh
Labels: documentation

#38 [Embedding] Support embedding StorageType LEVELDB.
  tensorflow/core/framework/embedding/config.proto
  tensorflow/core/framework/embedding/embedding_config.h
  tensorflow/core/framework/embedding/embedding_filter.h
  tensorflow/core/framework/embedding/embedding_var.h
  tensorflow/core/framework/embedding/value_ptr.h
  tensorflow/core/kernels/embedding_variable_ops_test.cc
  tensorflow/core/kernels/kv_variable_ops.cc
  tensorflow/core/kernels/training_ali_ops.cc
  tensorflow/core/ops/kv_variable_ops.cc
  tensorflow/python/__init__.py
  tensorflow/python/ops/embedding_variable_ops_test.py
  tensorflow/python/ops/kv_variable_ops.py
  tensorflow/python/ops/variable_scope.py
  tensorflow/python/ops/variables.py
  tensorflow/tools/api/golden/v1/tensorflow.pbtxt
  tensorflow/tools/compatibility/renames_v2.py
Labels: enhancement

#3 [BUILD] Fix cycle dependency when build TFServing.
  WORKSPACE
  tensorflow/core/BUILD
  tensorflow/core/kernels/data/BUILD
  tensorflow/workspace.bzl
  third_party/kafka.BUILD
  third_party/kafka/BUILD
  third_party/kafka/config.patch
Labels: bug

#53 [Runtime] Add TensorPoolAllocatorGPU for GPU, which reduce GPU memory usage.
  tensorflow/core/BUILD
  tensorflow/core/common_runtime/direct_session.cc
  tensorflow/core/common_runtime/direct_session.h
  tensorflow/core/common_runtime/gpu/gpu_device.cc
  tensorflow/core/common_runtime/gpu/gpu_process_state.cc
  tensorflow/core/common_runtime/gpu_memory_planner.cc
  tensorflow/core/common_runtime/gpu_memory_planner.h
  tensorflow/core/common_runtime/gpu_tensorpool_allocator.cc
  tensorflow/core/common_runtime/gpu_tensorpool_allocator.h
  tensorflow/core/common_runtime/gpu_tensorpool_allocator_test.cc
  tensorflow/core/common_runtime/size_class.h
  tensorflow/core/framework/allocator.h
  tensorflow/core/framework/tracking_allocator.cc
  tensorflow/core/framework/tracking_allocator.h
  tensorflow/core/graph/graph.cc
  tensorflow/core/graph/graph.h
Labels: enhancement

#55 [CIBUILD] Fix typo and update README.
  README.md
  docs/README/deeprec_dingtalk.png
  tensorflow/core/common_runtime/direct_session.cc
Labels: documentation

#57 [Embedding] Fix Hashtable Filter Config and Hashtable Embedding Lookup Op
  tensorflow/python/ops/hash_table/embedding.py
  tensorflow/python/ops/hash_table/hash_filter.py
  tensorflow/python/training/adam.py
Labels: bug

#59 [UT] Fix unit test failure of gpu_tensorpool_allocator_test.
  tensorflow/core/common_runtime/gpu_tensorpool_allocator_test.cc
Labels: unittest

#61 [Embedding] Fix HashTable Embedding package import
  tensorflow/python/ops/hash_table/embedding.py
Labels: bug

#6 [KafkaDataset] Add KafkaGroupIODataset to support consumer rebalance
  docs/KafkaDataset.md
  docs/index.md
  tensorflow/core/kernels/data/kafka_dataset_op.cc
  tensorflow/core/ops/dataset_ops.cc
  tensorflow/python/data/ops/readers.py
Labels: enhancement

#58 [Op] Fix ParallelDynamicStitch GPU implementation
  tensorflow/core/kernels/dynamic_stitch_op.cc
  tensorflow/core/kernels/dynamic_stitch_op_gpu.cu.cc
Labels: bug
