Repository alibaba/DeepRec, pull requests merged in 2022-05, with the labels that each got.

#209 [Modelzoo] Update model default epochs setting.
  modelzoo/DIEN/README.md
  modelzoo/DIEN/train.py
  modelzoo/DIN/README.md
  modelzoo/DIN/train.py
  modelzoo/DLRM/README.md
  modelzoo/DLRM/train.py
  modelzoo/DeepFM/README.md
  modelzoo/DeepFM/train.py
  modelzoo/WDL/README.md
  modelzoo/WDL/train.py
Labels: benchmark

#218 [Tests] Add modelzoo benchmark scripts.
  tests/model_benchmark/README.md
  tests/model_benchmark/benchmark.sh
  tests/model_benchmark/benchmark_result/checkpoint/README.md
  tests/model_benchmark/benchmark_result/log/README.md
  tests/model_benchmark/benchmark_result/record/script/README.md
  tests/model_benchmark/benchmark_result/record/tool/check_model.sh
  tests/model_benchmark/config.yaml
  tests/model_benchmark/log_process.py
Labels: benchmark

#216 [Op] Parallelize UnsortedSegment op.
  tensorflow/core/kernels/segment_reduction_ops.cc
  tensorflow/core/kernels/segment_reduction_ops_test.cc
  tensorflow/python/kernel_tests/segment_reduction_ops_test.py
Labels: enhancement

#223 [CIBUILD] Fix GPU contrib unit test.
  cibuild/gpu-ut/gpu-contrib-ut.sh
Labels: unittest

#221 [Tests] Add GPU benchmark option.
  tests/model_benchmark/README.md
  tests/model_benchmark/benchmark.sh
  tests/model_benchmark/config.yaml
Labels: benchmark

#226 [UT] Reduce memory consumption of EVAllocator unit tests.
  tensorflow/core/framework/ev_allocator_test.cc
Labels: unittest
