Repository alibaba/DeepRec, pull requests merged in 2022-02, with the labels that each got.

#65 Fix var_full_name is None in SaveSliceInfo.
  tensorflow/python/training/slot_creator.py
Labels: bug

#67 [Embedding] Fix the bug of the counter of lockless hashmap when deleting id.
  tensorflow/core/kernels/embedding_variable_ops_test.cc
  tensorflow/workspace.bzl
  third_party/0001-add-lockless-dense-hash-map.patch
  third_party/0001-fix-memory-leak-when-rebucket.patch
  third_party/0001-optimize-Size-function-when-lockless.patch
  third_party/add-lockless-dense-hash-map.patch
  third_party/thread_flag_when_erase_first.patch
Labels: bug

#70 [Embedding] Avoid fetching nullptr when using feature filter.
  tensorflow/workspace.bzl
  third_party/0001-Avoid-fetching-nullptr-when-use-featrue-filter.patch
Labels: bug

#73 [Embedding] Fix the bug when enable L2-weight eviction and counter filter at the same time.
  tensorflow/core/framework/embedding/embedding_var.h
Labels: bug

#72 [Embedding] Fix API compatibility of embedding columns.
  tensorflow/python/feature_column/feature_column_v2.py
Labels: bug

#71 [Allocator] Optimize EVAllocator with lower fragment and higher performance.
  tensorflow/core/BUILD
  tensorflow/core/framework/ev_allocator.cc
  tensorflow/core/framework/ev_allocator_test.cc
Labels: performance

#75 [Embedding] Fix: Graph is inconsistent in API ops.embedding_lookup().
  tensorflow/python/ops/embedding_ops.py
Labels: bug

#74 [Embedding] Remove EV_INIT from train.SessionManager.
  tensorflow/python/training/session_manager.py
Labels: bug

#49 [Embedding] Add experimental libpmem based PMEM allocator
  modelzoo/features/pmem/README.md
  modelzoo/features/pmem/benchmark.py
  scripts/install_pmem_dependencies.sh
  tensorflow/core/BUILD
  tensorflow/core/framework/allocator.cc
  tensorflow/core/framework/allocator.h
  tensorflow/core/framework/allocator_registry.cc
  tensorflow/core/framework/allocator_registry.h
  tensorflow/core/framework/embedding/config.proto
  tensorflow/core/framework/embedding/embedding_config.h
  tensorflow/core/framework/embedding/embedding_var.h
  tensorflow/core/framework/experimental_pmem_allocator.cc
  tensorflow/core/framework/experimental_pmem_allocator.h
  tensorflow/core/framework/experimental_pmem_allocator_utils.cc
  tensorflow/core/framework/experimental_pmem_allocator_utils.h
  tensorflow/core/framework/pmem_allocator.cc
  tensorflow/core/kernels/kv_variable_ops.cc
  tensorflow/core/ops/kv_variable_ops.cc
  tensorflow/python/ops/kv_variable_ops.py
  tensorflow/python/ops/variable_scope.py
  tensorflow/python/ops/variables.py
Labels: enhancement

#78 [Allocator] Fix PMEM allocator build failure and refactor code.
  tensorflow/core/framework/allocator.cc
  tensorflow/core/framework/allocator_registry.cc
  tensorflow/core/framework/allocator_registry.h
  tensorflow/core/framework/experimental_pmem_allocator.cc
  tensorflow/core/framework/experimental_pmem_allocator.h
  tensorflow/core/framework/experimental_pmem_allocator_utils.cc
  tensorflow/core/framework/experimental_pmem_allocator_utils.h
Labels: bug, refactoring

#77 [Allocator] Support batch allocate in EVAllocator.
  tensorflow/core/framework/allocator.h
  tensorflow/core/framework/ev_allocator.cc
  tensorflow/core/framework/ev_allocator_test.cc
  tensorflow/core/framework/tracking_allocator.cc
  tensorflow/core/framework/tracking_allocator.h
Labels: enhancement

#81 [Optimizer] An effective implementation of AdamOptimizer for sparse d…
  tensorflow/core/api_def/base_api/api_def_ResourceSparseApplyAdam.pbtxt
  tensorflow/core/api_def/base_api/api_def_SparseApplyAdam.pbtxt
  tensorflow/core/graph/graph.h
  tensorflow/core/kernels/training_ops.cc
  tensorflow/core/ops/training_ops.cc
  tensorflow/python/BUILD
  tensorflow/python/training/adam.py
  tensorflow/python/training/adam_sparse_test.py
  tensorflow/tools/api/golden/v1/tensorflow.-graph.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.-storage-option.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.data.-kafka-group-i-o-dataset.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.data.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.hash_table.-bloom-filter-lookup-hook.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.hash_table.-embedding-lookup-hook.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.hash_table.-read-only-hook.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.hash_table.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.raw_ops.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.-graph.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.hash_table.-bloom-filter-lookup-hook.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.hash_table.-embedding-lookup-hook.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.hash_table.-read-only-hook.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.hash_table.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.raw_ops.pbtxt
Labels: performance

#84 [Optimizer] Refactoring ResourceSparseApplyAdam and SparseApplyAdam ops.
  tensorflow/core/kernels/training_ops.cc
Labels: refactoring

#85 [Optimizer] Fix nadam_optimizer unit test failure.
  tensorflow/contrib/opt/python/training/nadam_optimizer.py
Labels: bug
