Repository alibaba/DeepRec, pull requests merged in 2022-04, with the labels that each got.

#135 [Embedding] Support restore frequency of features in EmbeddingVariable.
  tensorflow/core/framework/embedding/embedding_filter.h
  tensorflow/core/framework/embedding/embedding_var.h
  tensorflow/core/framework/embedding/multilevel_embedding.h
  tensorflow/core/kernels/embedding_variable_ops_test.cc
  tensorflow/core/kernels/kv_variable_ops.cc
  tensorflow/core/kernels/kv_variable_ops.h
Labels: enhancement

#141 [Embedding] Fix the bug of initialization of ValuePtr when using Dynamic-dimension Embedding Variable.
  tensorflow/core/framework/embedding/value_ptr.h
Labels: bug

#143 [Embedding] Fix StorageManager destructor core in EmbeddingVariable when eviction_thread exit.
  tensorflow/core/framework/embedding/multilevel_embedding.h
Labels: bug

#158 [Serving] Add build flag to optimize performance.
  serving/configure.py
Labels: performance

#62 [Embedding] Add CPU fused embedding ops.
  tensorflow/core/api_def/base_api/api_def_FusedSafeEmbeddingLookupSparseLocal.pbtxt
  tensorflow/core/api_def/base_api/api_def_FusedSafeEmbeddingLookupSparseLocalGrad.pbtxt
  tensorflow/core/kernels/BUILD
  tensorflow/core/kernels/fused_embedding/embedding_lookup_sparse_local_op.cc
  tensorflow/core/kernels/fused_embedding/embedding_lookup_sparse_local_op_test.cc
  tensorflow/core/kernels/fused_embedding/embedding_lookup_sparse_op.h
  tensorflow/core/kernels/fused_embedding/embedding_lookup_sparse_post_grad_op_test.cc
  tensorflow/core/kernels/fused_embedding/embedding_lookup_sparse_post_op.cc
  tensorflow/core/kernels/fused_embedding/embedding_lookup_sparse_post_op_test.cc
  tensorflow/core/kernels/fused_embedding/embedding_lookup_sparse_pre_op.cc
  tensorflow/core/kernels/fused_embedding/embedding_lookup_sparse_pre_op_test.cc
  tensorflow/core/ops/fused_embedding_ops.cc
  tensorflow/python/ops/fused_embedding_ops.py
Labels: performance

#21 [Embedding] EmbeddingVariable GPU impl
  cibuild/cpu-ut/cpu-python-ut.sh
  cibuild/gpu-ut.sh
  cibuild/gpu-ut/gpu-c-ut.sh
  cibuild/gpu-ut/gpu-cc-ut.sh
  cibuild/gpu-ut/gpu-contrib-ut.sh
  cibuild/gpu-ut/gpu-core-ut.sh
  cibuild/gpu-ut/gpu-examples-ut.sh
  cibuild/gpu-ut/gpu-java-ut.sh
  cibuild/gpu-ut/gpu-js-ut.sh
  cibuild/gpu-ut/gpu-python-ut.sh
  cibuild/gpu-ut/gpu-stream_executor-ut.sh
  docs/Embedding-Variable-GPU.md
  docs/index.md
  modelzoo/features/EmbeddingVariable/WDL/README.md
  modelzoo/features/EmbeddingVariable/WDL/train.py
  tensorflow/core/kernels/BUILD
  tensorflow/core/kernels/kv_variable_ops.cc
  tensorflow/core/kernels/kv_variable_ops_gpu.cu.cc
  tensorflow/core/kernels/kv_variable_ops_gpu.h
  tensorflow/core/kernels/training_ali_ops.cc
  tensorflow/core/kernels/training_ali_ops_gpu.cu.cc
  tensorflow/core/kernels/training_ali_ops_gpu.h
  tensorflow/python/BUILD
  tensorflow/python/ops/embedding_variable_ops_gpu_test.py
  tensorflow/python/ops/embedding_variable_ops_test.py
  tensorflow/workspace.bzl
  third_party/0001-cuco-modification-for-deeprec.patch
  third_party/cuco.BUILD
  third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc.tpl
Labels: enhancement

#182 [Embedding] Fix EVValueDumpIterator coredump which EV only has primar…
  tensorflow/core/framework/embedding/multilevel_embedding.h
  tensorflow/core/kernels/kv_variable_ops.h
Labels: bug

#187 [Modelzoo] Rebuild WDL to update API and enable DeepRec features.
  modelzoo/WDL/Dockerfile
  modelzoo/WDL/README.md
  modelzoo/WDL/distribute_k8s/distribute_k8s_BF16.yaml
  modelzoo/WDL/distribute_k8s/distribute_k8s_FP32.yaml
  modelzoo/WDL/distribute_k8s/launch.py
  modelzoo/WDL/train.py
Labels: demo

#188 [Modelzoo] Rebuild DeepFM to update API and enable DeepRec features.
  modelzoo/DeepFM/Dockerfile
  modelzoo/DeepFM/README.md
  modelzoo/DeepFM/distribute_k8s/distribute_k8s_BF16.yaml
  modelzoo/DeepFM/distribute_k8s/distribute_k8s_FP32.yaml
  modelzoo/DeepFM/distribute_k8s/launch.py
  modelzoo/DeepFM/train.py
Labels: demo

#190 [Modelzoo] Rebuild DSSM to update API and enable DeepRec features.
  modelzoo/DSSM/DockerFile
  modelzoo/DSSM/README.md
  modelzoo/DSSM/distribute_k8s/distribute_k8s_BF16.yaml
  modelzoo/DSSM/distribute_k8s/distribute_k8s_FP32.yaml
  modelzoo/DSSM/distribute_k8s/launch.py
  modelzoo/DSSM/train.py
Labels: demo

#191 [Modelzoo] Rebuild DIN to update API and enable DeepRec features.
  modelzoo/DIN/DockerFile
  modelzoo/DIN/README.md
  modelzoo/DIN/distribute_k8s/distribute_k8s_BF16.yaml
  modelzoo/DIN/distribute_k8s/distribute_k8s_FP32.yaml
  modelzoo/DIN/distribute_k8s/launch.py
  modelzoo/DIN/result/README.md
  modelzoo/DIN/train.py
Labels: demo

#192 [Modelzoo] Rebuild DIEN to update API and enable DeepRec features.
  modelzoo/DIEN/DockerFile
  modelzoo/DIEN/README.md
  modelzoo/DIEN/distribute_k8s/distribute_k8s_BF16.yaml
  modelzoo/DIEN/distribute_k8s/distribute_k8s_FP32.yaml
  modelzoo/DIEN/distribute_k8s/launch.py
  modelzoo/DIEN/result/README.md
  modelzoo/DIEN/train.py
Labels: demo

#193 [Docs] Update README.md and Compile-And-Install.md.
  README.md
  docs/DeepRec-Compile-And-Install.md
  docs/Estimator-Compile-And-Install.md
  docs/TFServing-Compile-And-Install.md
  docs/index.md
Labels: documentation

#196 [Docs] Add Emebedding Variable Export Format document.
  docs/Embedding-Variable-Export-Format.md
  docs/index.md
Labels: documentation
