Repository alibaba/DeepRec, pull requests merged in 2022-03, with the labels that each got.

#96 [Modelzoo] Fix an acc calculation bug.
  modelzoo/DLRM/train.py
  modelzoo/DSSM/train.py
  modelzoo/DeepFM/train.py
  modelzoo/WDL/train.py
Labels: bug

#99 [CIBUILD] Fix: define TENSORFLOW_USE_PMEM macro when enable PMEM in c…
  tensorflow/core/BUILD
  tensorflow/core/framework/allocator.cc
  tensorflow/core/framework/allocator_registry.cc
  tensorflow/core/framework/allocator_registry.h
  tensorflow/core/platform/default/build_config.bzl
Labels: bug

#106 [Allocator] Revert dbb831c0bca5edcddbdc5ba329f267edcf8b9f42 to fix ra…
  tensorflow/core/framework/ev_allocator.cc
Labels: bug

#115 [SavedModel] simple_save api support dump incremental graph info.
  tensorflow/python/saved_model/simple_save.py
  tensorflow/tools/api/golden/v1/tensorflow.saved_model.pbtxt
Labels: enhancement

#120 [Doc] Update CODE_OF_CONDUCT.md CONTRIBUTING.md ISSUE_TEMPLATE.md and RELEASE.md.
  CODEOWNERS
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  ISSUE_TEMPLATE.md
  RELEASE.md
Labels: documentation

#114 [Embedding] Fix coredump when destruct FAE object and enable auto selection of ValuePtr.
  tensorflow/core/framework/embedding/embedding_config.h
  tensorflow/core/framework/embedding/embedding_filter.h
  tensorflow/core/framework/embedding/embedding_var.h
  tensorflow/core/framework/embedding/multilevel_embedding.h
  tensorflow/core/framework/embedding/value_ptr.h
  tensorflow/core/kernels/embedding_variable_ops_test.cc
  tensorflow/core/kernels/kv_variable_ops.cc
  tensorflow/python/ops/embedding_variable_ops_test.py
  tensorflow/python/ops/kv_variable_ops.py
Labels: bug

#124 [Modelzoo] Enable dump saved_model and incremental_checkpoint.
  modelzoo/features/EmbeddingVariable/WDL/train.py
Labels: demo

#113 [Doc] Add PMEM allocator and Embedding on PMEM.
  docs/Embedding-on-PMEM.md
  docs/PMEM.md
  docs/PMEM/fsdax_allocator.png
  docs/PMEM/kmemdax.png
  docs/PMEM/memkind.png
  docs/PMEM/memory_mode.png
  docs/index.md
Labels: documentation
