Repository alibaba/DeepRec, pull requests merged in 2022-06, with the labels that each got.

#229 [BUILD] Fix compile error when use gcc-8.3.
  tensorflow/core/kernels/unique_ali_op_util.h
  tensorflow/tensorflow.bzl
Labels: build environment

#220 [UT] Fix embedding_variable_ops_gpu_test ut.
  tensorflow/python/ops/embedding_variable_ops_gpu_test.py
Labels: bug, unittest

#224 [Embedding] Add SSD HashKV storage for EmbeddingVariable.
  tensorflow/core/framework/embedding/cache.h
  tensorflow/core/framework/embedding/config.proto
  tensorflow/core/framework/embedding/kv_interface.h
  tensorflow/core/framework/embedding/leveldb_kv.h
  tensorflow/core/framework/embedding/multilevel_embedding.h
  tensorflow/core/framework/embedding/ssd_hashkv.h
  tensorflow/core/framework/embedding/value_ptr.h
  tensorflow/core/kernels/BUILD
  tensorflow/core/kernels/embedding_variable_ops_test.cc
  tensorflow/core/kernels/kv_variable_ops.cc
  tensorflow/core/kernels/save_restore_tensor.h
  tensorflow/core/ops/kv_variable_ops.cc
  tensorflow/python/ops/embedding_variable_ops_test.py
  tensorflow/python/ops/kv_variable_ops.py
  tensorflow/python/ops/variables.py
  third_party/0001-Avoid-fetching-nullptr-when-use-featrue-filter.patch
Labels: enhancement

#251 [Checkpoint] Fix: delete old incremental checkpoint file failed.
  tensorflow/python/training/incremental_saver.py
Labels: bug

#248 [Modelzoo] Add DBMTL model.
  modelzoo/DBMTL/README.md
  modelzoo/DBMTL/data/README.md
  modelzoo/DBMTL/distribute_k8s/distribute_k8s_BF16.yaml
  modelzoo/DBMTL/distribute_k8s/distribute_k8s_FP32.yaml
  modelzoo/DBMTL/distribute_k8s/launch.py
  modelzoo/DBMTL/result/README.md
  modelzoo/DBMTL/train.py
  modelzoo/README.md
Labels: enhancement

#249 [Modelzoo] Add MMoE model.
  modelzoo/MMoE/README.md
  modelzoo/MMoE/data/README.md
  modelzoo/MMoE/distribute_k8s/distribute_k8s_BF16.yaml
  modelzoo/MMoE/distribute_k8s/distribute_k8s_FP32.yaml
  modelzoo/MMoE/distribute_k8s/launch.py
  modelzoo/MMoE/result/README.md
  modelzoo/MMoE/train.py
  modelzoo/README.md
Labels: enhancement

#240 [Op] Optimize unsorted segment sum on 1 dim.
  tensorflow/core/BUILD
  tensorflow/core/kernels/BUILD
  tensorflow/core/kernels/segment_reduction_ops.cc
  tensorflow/core/kernels/segment_reduction_ops_test.cc
  tensorflow/core/util/test_util.h
Labels: enhancement

#269 [CUDA] Fix build failure with cuda11.6.
  tensorflow/core/kernels/BUILD
  tensorflow/core/kernels/batched_non_max_suppression_op.cu.cc
  tensorflow/core/kernels/bincount_op_gpu.cu.cc
  tensorflow/core/kernels/dynamic_partition_op_gpu.cu.cc
  tensorflow/core/kernels/fused_embedding/fused_embedding_post_ops_gpus.cu.cc
  tensorflow/core/kernels/fused_embedding/fused_embedding_pre_ops_gpus.cu.cc
  tensorflow/core/kernels/generate_box_proposals_op.cu.cc
  tensorflow/core/kernels/histogram_op_gpu.cu.cc
  tensorflow/core/kernels/non_max_suppression_op.cu.cc
  tensorflow/core/kernels/reduction_gpu_kernels.cu.h
  tensorflow/core/kernels/scan_ops_gpu.h
  tensorflow/core/kernels/topk_op_gpu.h
  tensorflow/core/kernels/where_op_gpu.cu.h
  third_party/cub.BUILD
  third_party/gpus/cuda/BUILD.tpl
  third_party/gpus/cuda/BUILD.windows.tpl
  third_party/gpus/cuda_configure.bzl
Labels: bug

#273 [Embedding] Add fusion option in feature_column.share_embedding_columns.
  tensorflow/python/feature_column/feature_column.py
  tensorflow/python/feature_column/feature_column_v2.py
Labels: enhancement

#283 [Embedding] Fix wrong type in SparseApplyOp, Tindex/Tkey -> int64.
  tensorflow/core/kernels/training_ali_ops.cc
Labels: bug

#284 [Embedding] ConstOp(DType=tstring) donnot colocate with KvVarHandleOp.
  tensorflow/python/training/saving/saveable_object_util.py
Labels: bug

#286 [Runtime] Fix shared resource_mgr double free corruption bug.
  tensorflow/core/common_runtime/device.cc
  tensorflow/core/common_runtime/device.h
  tensorflow/core/common_runtime/direct_session.cc
  tensorflow/core/public/session.h
Labels: bug
